services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: ["tail", "-f", "/dev/null"]

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "cli/file_rest.py"]
